### ISSUE TITLE
site page `https://kazu-yamamoto.github.io/mighttpd2/` is 404 

### ISSUE THREAD

**Issue by chenrui333** [kazu-yamamoto/mighttpd2#28]
👋 Looks like the site page `https://kazu-yamamoto.github.io/mighttpd2/` is 404 atm.

```
$ curl -I https://kazu-yamamoto.github.io/mighttpd2/
HTTP/2 404
server: GitHub.com
content-type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
etag: "65b99465-239b"
```

**Comment by kazu-yamamoto** [comment]
Thank you very much for letting me know this.
This is a side-effect of the transition from `master` to `main`.
This issue has been fixed.
